CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    gender SMALLINT NULL, -- 0: Nữ, 1: Nam, 2: Khác
    facebook_account_id VARCHAR(255) NULL,
    google_account_id VARCHAR(255) NULL,
    phone VARCHAR(20) NULL,
    dob DATE NULL,
    role_id BIGINT REFERENCES roles (role_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();