CREATE TABLE IF NOT EXISTS addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    province_id INT NOT NULL,
    district_id INT NOT NULL,
    ward_code VARCHAR(20) NOT NULL,
    full_address VARCHAR(255) NULL,
    street_number VARCHAR(100) NULL,
    is_default BOOLEAN DEFAULT FALSE,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
);