CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(100) NOT NULL UNIQUE,
    category_name VARCHAR(200) NOT NULL,
    category_status SMALLINT DEFAULT 1, -- 0: Ẩn, 1: Hiển thị
    level INT DEFAULT 1, -- Cấp độ của cây danh mục đa cấp (1: Cha, 2: Con...)
    parent_id BIGINT REFERENCES categories (category_id) ON DELETE SET NULL,
    icon_url VARCHAR(500) NULL,
    target_demographic SMALLINT NULL,
    category_type VARCHAR(30) DEFAULT 'STANDARD' NOT NULL,
    display_order INT DEFAULT 0 NOT NULL
);

CREATE INDEX idx_categories_demographic ON categories (
    target_demographic,
    category_type
);