CREATE TABLE IF NOT EXISTS products (
	product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_slug VARCHAR(100) NOT NULL UNIQUE,
	product_name VARCHAR(150) NOT NULL,
    product_description TEXT NULL,
	in_popular BOOLEAN DEFAULT FALSE,
	in_stock BOOLEAN DEFAULT TRUE,
	target_gender SMALLINT DEFAULT 2, -- 0: Nữ, 1: Nam, 2: Unisex – Recommendation
    max_order_quantity INT DEFAULT 0,
    options_config JSONB NULL,
    product_tags JSONB DEFAULT '[]'::jsonb, -- Ví dụ: '[vintage, oversize, mùa hè]'
	category_id BIGINT REFERENCES categories(category_id) ON DELETE SET NULL,
	weight_kg DECIMAL(5,2) DEFAULT 0.10, -- Trọng lượng thực (Phục vụ GHN package_detail)
	length_m DECIMAL(5,2) DEFAULT 0.10,  -- Chiều dài theo mét
	width_m DECIMAL(5,2) DEFAULT 0.10,   -- Chiều rộng theo mét
	height_m DECIMAL(5,2) DEFAULT 0.10,   -- Chiều cao theo mét
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    -- Cột phục vụ tìm kiếm Full-text Search 
    search_vector TSVECTOR NULL 
);

CREATE OR REPLACE FUNCTION products_search_trigger() RETURNS trigger AS $$
BEGIN
  -- Nối Tên và Mô tả lại để đánh index (Trọng số Tên 'A' cao hơn Mô tả 'B')
  NEW.search_vector :=
    setweight(to_tsvector('simple', unaccent(coalesce(NEW.product_name, ''))), 'A') ||
    setweight(to_tsvector('simple', unaccent(coalesce(NEW.product_description, ''))), 'B');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- 3. Gắn Trigger vào bảng products để lắng nghe sự kiện
CREATE TRIGGER tsvectorupdate 
BEFORE INSERT OR UPDATE ON products 
FOR EACH ROW EXECUTE FUNCTION products_search_trigger();

-- 4. Đánh GIN Index tối ưu tốc độ tìm kiếm từ khóa
CREATE INDEX idx_products_search ON products USING GIN (search_vector);

-- =====================================================================
-- CHỈ MỤC TỐI ƯU HÓA HIỆU NĂNG TÌM KIẾM (INDEXING)
-- =====================================================================

-- Tạo GIN Index ngay sau khi tạo bảng Products để tối ưu tốc độ cho toán tử @>
CREATE INDEX IF NOT EXISTS idx_products_product_tags_gin ON products USING gin (product_tags jsonb_path_ops);

-- Bổ sung Index cho các cột thường xuyên được dùng để Lọc (Filter)
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);