CREATE TABLE IF NOT EXISTS product_variants (
    variant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products (product_id) ON DELETE CASCADE,
    price NUMERIC(15, 2) NOT NULL,
    cost_price NUMERIC(15, 2) NOT NULL,
    variant_attributes JSONB NOT NULL,
    sku_code VARCHAR(50) NOT NULL UNIQUE,
    variant_image VARCHAR(500) NULL,
    stock_quantity INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    locked_stock INT DEFAULT 0 NOT NULL
);

ALTER TABLE product_variants
ADD CONSTRAINT chk_stock_valid CHECK (stock_quantity >= 0);

ALTER TABLE product_variants
ADD CONSTRAINT chk_locked_non_negative CHECK (locked_stock >= 0);

CREATE TABLE IF NOT EXISTS product_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products (product_id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL,
    is_thumbnail BOOLEAN DEFAULT FALSE, -- Cờ đánh dấu đây là ảnh bìa chính
    display_order INT DEFAULT 0 -- Thứ tự sắp xếp ảnh vuốt sang ngang
);