CREATE TABLE IF NOT EXISTS inventory_transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES product_variants (variant_id) ON DELETE CASCADE,
    quantity_change INT NOT NULL, -- Giá trị âm (xuất kho), Giá trị dương (nhập kho)
    transaction_type VARCHAR(50) NOT NULL, -- 'IMPORT', 'ORDER', 'RETURN', 'ADJUSTMENT'
    reference_id BIGINT NULL, -- Chứa order_id, return_id hoặc phiếu nhập kho tương ứng
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);