CREATE TABLE IF NOT EXISTS orders (
order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL DEFAULT CURRENT_DATE,
    shipping_date DATE NULL,
    payment_method SMALLINT NOT NULL,  -- 0: COD, 1: VNPAY, 2: MOMO
    shipping_method SMALLINT NOT NULL, -- 0: Giao hàng nhanh, 1: Hỏa tốc (Ahamove/GHN)
    delivery_order_id VARCHAR(50) NULL, 
    delivery_status VARCHAR(50) DEFAULT 'PENDING', 
    tracking_number VARCHAR(100) NOT NULL, 
    note VARCHAR(200) NULL,
    address_id BIGINT REFERENCES addresses(address_id) ON DELETE RESTRICT,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    order_status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    device_session_id BIGINT REFERENCES device_sessions(device_session_id),

-- TẦNG 1: TIỀN HÀNG VÀ VOUCHER CỦA SHOP
total_product_money NUMERIC(15, 2) NOT NULL, -- Tổng tiền hàng gốc (Bằng tổng total_money của các order_details)
shop_discount_amount NUMERIC(15, 2) DEFAULT 0.00, -- Số tiền được giảm từ mã của Shop (Mã giảm tiền hàng)

-- TẦNG 2: PHÍ VẬN CHUYỂN VÀ VOUCHER FREESHIP
original_shipping_fee NUMERIC(15, 2) DEFAULT 0.00, -- Phí ship gốc do API GHN/Ahamove trả về
shipping_discount_amount NUMERIC(15, 2) DEFAULT 0.00, -- Số tiền được giảm từ mã Freeship

-- TẦNG 3: VOUCHER THANH TOÁN (VNPAY/MOMO)
payment_discount_amount NUMERIC(15, 2) DEFAULT 0.00, -- Số tiền được giảm từ mã của đối tác thanh toán

-- KẾT QUẢ CUỐI CÙNG

final_payment_money NUMERIC(15,2) NOT NULL           -- Số tiền cuối cùng khách phải trả

);