CREATE TABLE IF NOT EXISTS order_details (
    order_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_of_product INT NOT NULL,
    order_detail_price DECIMAL(12, 2) NOT NULL,
    total_money DECIMAL(12, 2) NOT NULL,
    item_status VARCHAR(30) DEFAULT 'NORMAL' NOT NULL,
    order_id BIGINT REFERENCES orders (order_id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES product_variants (variant_id) ON DELETE RESTRICT
);