CREATE TABLE IF NOT EXISTS coupon_usages (
    coupon_usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    coupon_id BIGINT REFERENCES coupons (coupon_id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES orders (order_id) ON DELETE CASCADE,
    used_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE coupon_usages
ADD CONSTRAINT uq_coupon_usage UNIQUE (user_id, coupon_id, order_id);