CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products (product_id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES orders (order_id) ON DELETE CASCADE, -- Đảm bảo review bắt buộc gắn liền với đơn hàng đã mua
    rating INT NOT NULL CHECK (
        rating >= 1
        AND rating <= 5
    ),
    comment TEXT NULL,
    review_status VARCHAR(20) DEFAULT 'PENDING' NOT NULL, -- 'PENDING', 'APPROVED', 'HIDDEN'
    reply_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER trg_reviews_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TABLE IF NOT EXISTS review_images (
    review_image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT REFERENCES reviews (review_id) ON DELETE CASCADE,
    image_url VARCHAR(500) NOT NULL -- Link lưu trên Cloudinary
);