CREATE TABLE IF NOT EXISTS device_sessions (
    device_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL REFERENCES users (user_id) ON DELETE SET NULL,
    session_id VARCHAR(100) NOT NULL UNIQUE,
    ip_address VARCHAR(45) NOT NULL,
    user_agent VARCHAR(500) NOT NULL,
    device_fingerprint VARCHAR(255) NULL, -- Canvas / WebGL fingerprint hash từ FE
    location_country VARCHAR(100) NULL,
    is_vpn_proxy BOOLEAN DEFAULT FALSE, -- Cảnh báo IP bẩn
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);