-- 5. Nhãn dữ liệu thực tế (Ground Truth Labels phục vụ MLOps Feedback Loop)
CREATE TABLE IF NOT EXISTS fraud_records_and_labels (
    fraud_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES orders (order_id) ON DELETE CASCADE,
    risk_score DECIMAL(5, 2) NOT NULL, -- Điểm số AI (0.00 - 100.00)
    system_decision VARCHAR(50) NOT NULL, -- 'APPROVE', 'REVIEW', 'DECLINE'
    final_label VARCHAR(100) NOT NULL DEFAULT 'PENDING',
    -- 'ecommerce_marked_as_approved' (đơn sạch), 'ecommerce_chargeback_fraud' (gian lận thẻ)...
    labeled_by BIGINT NULL REFERENCES users (user_id) ON DELETE SET NULL,
    analyst_notes TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_fraud_labels_updated_at
BEFORE UPDATE ON fraud_records_and_labels
FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();