-- Bảng trung chuyển lưu URL ảnh đã upload lên S3 nhưng chưa được liên kết với entity nghiệp vụ.
-- Cleanup job sẽ quét và xóa các bản ghi cũ hơn 24 giờ.
CREATE TABLE IF NOT EXISTS temp_uploads (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url        TEXT   NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Index tăng tốc truy vấn cleanup theo thời gian
CREATE INDEX IF NOT EXISTS idx_temp_uploads_created_at ON temp_uploads (created_at);
