-- ══════════════════════════════════════════════════════════════════════
-- V5.12 — Create payments table (Brand New)
-- Tách lịch sử thanh toán thành bảng riêng — 1 order có thể có
-- nhiều payment record (thử lại, hoàn tiền, v.v.)
-- ══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS payments (
    payment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    payment_method SMALLINT NOT NULL,                            -- 0: COD, 1: VNPAY, 2: MOMO
    amount         NUMERIC(15, 2) NOT NULL,
    transaction_id VARCHAR(255) NULL,                            -- Mã giao dịch từ cổng thanh toán
    payment_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',       -- PENDING / PAID / FAILED / REFUNDED
    paid_at        TIMESTAMPTZ NULL,                             -- Thời điểm thanh toán thành công
    created_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Index hỗ trợ tra cứu lịch sử thanh toán theo order
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
