-- ══════════════════════════════════════════════════════════════════════
-- V5.13 — Create notifications table (Brand New)
-- In-app notification: thông báo trạng thái đơn hàng, hệ thống, v.v.
-- ══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS notifications (
    notification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    title             VARCHAR(200) NOT NULL,
    content           TEXT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,   -- ORDER_UPDATE / SYSTEM / PROMOTION ...
    reference_id      BIGINT NULL,            -- order_id / product_id tuỳ notification_type
    is_read           BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Composite index: tối ưu query "lấy thông báo chưa đọc của user X"
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read);
