-- PHÂN HỆ 8: CHĂM SÓC KHÁCH HÀNG & QUẢN TRỊ RỦI RO (RISK & SUPPORT)
-- =====================================================================

CREATE TABLE IF NOT EXISTS contact_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL REFERENCES users(user_id) ON DELETE SET NULL, -- Bảo toàn lịch sử
    guest_name VARCHAR(100) NULL,  -- Bắt buộc phải có để khách vãng lai xưng danh
    guest_email VARCHAR(100) NULL, -- Bắt buộc phải có để Admin gửi email phản hồi
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_contact_status CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED'))
);
-- Chỉ cần đúng 1 Index này để Admin Dashboard tải danh sách thư mới nhất lên đầu
CREATE INDEX idx_contact_dashboard ON contact_messages (status, created_at DESC);
