-- Drop old fraud tables
DROP TABLE IF EXISTS fraud_records CASCADE;
DROP TABLE IF EXISTS fraud_rule_configs CASCADE;

-- Create risk_rule_configs
CREATE TABLE IF NOT EXISTS risk_rule_configs (
    rule_code VARCHAR(50) PRIMARY KEY,
    rule_name VARCHAR(255) NOT NULL,
    risk_level VARCHAR(20) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    threshold_value NUMERIC(15,2) NOT NULL,
    time_window_minutes INT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_risk_rule_configs_updated_at
BEFORE UPDATE ON risk_rule_configs
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

-- Create risk_alerts
CREATE TABLE IF NOT EXISTS risk_alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES orders(order_id) ON DELETE SET NULL,
    rule_code VARCHAR(50) NOT NULL REFERENCES risk_rule_configs(rule_code) ON DELETE CASCADE,
    description TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_risk_status CHECK (status IN ('PENDING', 'REVIEWING', 'RESOLVED', 'FALSE_POSITIVE'))
);

